<!-- (A) HEADER -->
<header class="cb-head">
  <!-- (A1) TITLE -->
  <h1 class="cb-head-title">My Pictures</h1>

  <!-- (A2) BUTTONS -->
  <div class="cb-head-btn">
    <a class="btn-ico mi" href="#home">reply</a>
  </div>
</header>

<!-- (B) GALLERY PICTURES -->
<div id="gallery-pics"></div>
<template id="gallery-template"><div class="pic">
  <img class="img"/>
  <div class="btn">
    <button class="mi del">delete</button>
    <button class="mi get">file_download</button>
  </div>
</div></template>
